version: '3'

services:

 desafio:
  build: .
  image: erigamonte/desafio
  container_name: desafio
  ports: 
   - "8080:8080"
  networks:
   - desafio_network
  depends_on:
   - "db"

 db:
  image: mysql:5.6
  environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD=1
   - MYSQL_DATABASE=desafio_db
  ports: 
   - "3306:3306"
  networks:
   - desafio_network
   
 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
   - db
  ports:
   - 80:80
  environment:
   - PMA_ARBITRARY=1
  depends_on:
   - "db"
  networks:
   - desafio_network

networks:
 desafio_network:
  driver: bridge
